version: "3.7"

networks:
  development-network:
    name: development_network
    
volumes:
  database-data:
    driver: local
  kafka-data:
    driver: local 

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456    
    ports:
      - 5435:5432    
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - development-network

  api:
    image: currencyexchangeapi:dev
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database